version: '3'
services:
  db:
    container_name: postgres
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: autopark
    image: 200605030904/autopark:0.1
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped